name: Node.js CI/CD with Coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
   # - name: Install dependencies
   #   run: npm ci

    # Step 4: Run tests
    - name: Run unit tests
      run: npm run test:unit

    - name: Run BDD tests
      run: npm run test:bdd

    # Step 5: Run coverage
    - name: Run coverage tests
      run: npm run coverage

    # Step 6: Upload Coverage Reports
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
