name: Node.js CI/CD with NPM
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can adjust the version as needed
 
    - name: Install dependencies
      run: npm install

    - name: Install mocha
      run: npm install -g mochawesome mochawesome-report-generator
 
    - name: unit test
      run: npm run test:unit --logger "trx:LogFilename=xtest.trx"

    - name: BDD test
      run: npm run test:bdd

    #- name: atdd test
    #  run: npm run test:atdd
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        trx.files: "*/test-results/**/xtest.trx"
